services:
  database:
    image: postgres:latest
    restart: always
    container_name: matchify-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=matchify-dev-db
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    depends_on:
      - database
    image: redis:latest
    container_name: matchify-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
